<% director_uuid = 'CHANGE-ME' %>
<% deployment_name = 'shipyard' %>
<% elastic_ip = 'CHANGE-ME' %>
<% tld = 'microbosh' %>
<% num_nodes = 5 %>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: shipyard
   version: latest

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.xlarge

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: <%= 1 + num_nodes %>
  serial: false

networks:
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
        - bosh
        - <%= deployment_name %>

  - name: elastic
    type: vip
    cloud_properties: {}

resource_pools:
  - name: shipyard
    network: default
    size: 1
    stemcell:
      name: bosh-aws-xen-ubuntu
      version: latest
    cloud_properties:
      instance_type: m1.xlarge

  - name: nodes
    network: default
    size: <%= num_nodes %>
    stemcell:
      name: bosh-aws-xen-ubuntu
      version: latest
    cloud_properties:
      instance_type: m1.xlarge

jobs:
  - name: shipyard
    templates:
      - name: docker
      - name: shipyard_db
      - name: shipyard_redis
      - name: shipyard_router
      - name: shipyard_lb
      - name: shipyard
    instances: 1
    resource_pool: shipyard
    persistent_disk: 65536
    networks:
      - name: default
        default: [dns, gateway]
      - name: elastic
        static_ips:
          - <%= elastic_ip %>

  - name: node
    templates:
      - name: docker
      - name: shipyardagent
    instances: <%= num_nodes %>
    resource_pool: nodes
    networks:
      - name: default
        default: [dns, gateway]

properties:
  shipyard:
    host: 0.shipyard.default.<%= deployment_name %>.<%= tld %>
    db:
      host: 0.shipyard.default.<%= deployment_name %>.<%= tld %>
    redis:
      host: 0.shipyard.default.<%= deployment_name %>.<%= tld %>
    lb:
      routers:
        - 0.shipyard.default.<%= deployment_name %>.<%= tld %>
